
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shoppingmall
    username: root
    password: green502
    #mybatis
mybatis:
  type-aliases-package: com.green.shopingmall
  mapper-locations: mapper/**/*.xml

#SWAGGER
springdoc:

  swagger-ui:
    path: /swagger.html
    operations-sorter : method


file:
  dir: D:\download\
